### ISSUE TITLE
App doesn't build

### ISSUE THREAD

**Issue by thomwiggers** [credentials/irma_android_management#26]
it depends on `irma_android_library`, which doesn't appear to exist in the online repos.

**Comment by sietseringers** [comment]
Hmm, are you sure you mean this app and not the [card emulator](https://github.com/credentials/irma_android_cardemu)? The version that this app depends on is [right here](https://github.com/credentials/credentials.github.io/tree/master/repos/maven2/org/irmacard/android/irma_android_library/0.9.1), while I have indeed not yet uploaded the version that the cardemu depends on. Anyway, I'll do that tomorrow.

**Comment by thomwiggers** [comment]
we (cc @koen92) weren't able to without getting 0.9.2 from the repo, renaming it to 0.9.1 and `gradle install`ing it

**Comment by sietseringers** [comment]
You're right! I moved some classes from the managemant app to `irma_android_library` a while ago, and then forgot to bump the version number of the `irma_android_library` dependency - so it could not find the moved classes. Fixed now, thanks!
